import React, { useState } from 'react';
import { X, Link2, Download, FileText, Check, Copy, Printer, FileCode } from 'lucide-react';
import { ChatSession, Message } from '../types';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  session: ChatSession | null;
  selectedMessage?: Message | null;
}

export const ShareModal: React.FC<ShareModalProps> = ({
  isOpen,
  onClose,
  session,
  selectedMessage,
}) => {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedText, setCopiedText] = useState(false);

  if (!isOpen || !session) return null;

  const messagesToExport = selectedMessage ? [selectedMessage] : session.messages;

  // Generate Markdown representation
  const generateMarkdown = () => {
    let md = `# ${session.title || 'Zorvik AI Conversation'}\n\n`;
    md += `*Generated by Zorvik AI on ${new Date().toLocaleString()}*\n\n---\n\n`;

    messagesToExport.forEach((msg) => {
      const roleName = msg.role === 'user' ? '👤 **User**' : '⚡ **Zorvik AI**';
      md += `${roleName} *(${new Date(msg.timestamp).toLocaleTimeString()})*:\n\n${msg.content}\n\n---\n\n`;
    });

    return md;
  };

  // Copy shareable link
  const handleCopyLink = () => {
    const url = `${window.location.origin}/app?chat=${session.id}`;
    navigator.clipboard.writeText(url);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2200);
  };

  // Copy plain text/markdown
  const handleCopyTranscript = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopiedText(true);
    setTimeout(() => setCopiedText(false), 2200);
  };

  // Download Markdown file (.md)
  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${session.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'zorvik-ai-chat'}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Download Standalone Styled HTML Report (.html)
  const handleDownloadHTMLReport = () => {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${session.title} — Zorvik AI Report</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      background-color: #050510;
      color: #e2e8f0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      line-height: 1.65;
      padding: 40px 20px;
      max-width: 860px;
      margin: 0 auto;
    }
    h1 {
      color: #fff;
      font-size: 26px;
      border-bottom: 1px solid rgba(255,255,255,0.1);
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .badge {
      display: inline-block;
      padding: 4px 10px;
      border-radius: 9999px;
      background: rgba(147, 51, 234, 0.15);
      border: 1px solid rgba(147, 51, 234, 0.3);
      color: #c084fc;
      font-size: 11px;
      font-family: monospace;
      margin-bottom: 24px;
    }
    .turn {
      margin-bottom: 28px;
      padding: 20px;
      border-radius: 12px;
      background: rgba(255,255,255,0.02);
      border: 1px solid rgba(255,255,255,0.06);
    }
    .turn-user {
      border-left: 3px solid #22d3ee;
    }
    .turn-assistant {
      border-left: 3px solid #9333ea;
    }
    .role {
      font-size: 12px;
      font-family: monospace;
      font-weight: 600;
      text-transform: uppercase;
      margin-bottom: 8px;
      display: flex;
      justify-content: space-between;
    }
    .role-user { color: #22d3ee; }
    .role-assistant { color: #c084fc; }
    .timestamp { color: #64748b; font-size: 11px; font-weight: normal; }
    .content { white-space: pre-wrap; font-size: 14px; word-break: break-word; }
    .footer { margin-top: 40px; border-top: 1px solid rgba(255,255,255,0.08); padding-top: 16px; font-size: 11px; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <div class="badge">Zorvik AI Executive Export</div>
  <h1>${session.title || 'Conversation Archive'}</h1>
  ${messagesToExport
    .map(
      (m) => `
    <div class="turn ${m.role === 'user' ? 'turn-user' : 'turn-assistant'}">
      <div class="role ${m.role === 'user' ? 'role-user' : 'role-assistant'}">
        <span>${m.role === 'user' ? 'User' : 'Zorvik AI'}</span>
        <span class="timestamp">${new Date(m.timestamp).toLocaleString()}</span>
      </div>
      <div class="content">${m.content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
    </div>
  `
    )
    .join('')}
  <div class="footer">Exported from Zorvik AI on ${new Date().toLocaleString()} • Confidential & Proprietary</div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${session.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'zorvik-ai-report'}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Download JSON file (.json)
  const handleDownloadJSON = () => {
    const jsonStr = JSON.stringify(
      {
        id: session.id,
        title: session.title,
        exportedAt: new Date().toISOString(),
        messages: messagesToExport,
      },
      null,
      2
    );
    const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${session.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'zorvik-ai-chat'}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Print to PDF / Browser Print
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${session.title} — Zorvik AI</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; padding: 40px; color: #111; max-width: 800px; margin: 0 auto; }
            h1 { font-size: 24px; border-bottom: 2px solid #eee; padding-bottom: 12px; margin-bottom: 24px; }
            .turn { margin-bottom: 24px; padding-bottom: 16px; border-bottom: 1px solid #f0f0f0; }
            .role { font-weight: 600; font-size: 14px; text-transform: uppercase; color: #666; margin-bottom: 6px; }
            .content { white-space: pre-wrap; font-size: 15px; }
            .meta { font-size: 12px; color: #999; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 8px; }
          </style>
        </head>
        <body>
          <h1>${session.title}</h1>
          ${messagesToExport
            .map(
              (m) => `
            <div class="turn">
              <div class="role">${m.role === 'user' ? 'You' : 'Zorvik AI'}</div>
              <div class="content">${m.content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
            </div>
          `
            )
            .join('')}
          <div class="meta">Exported from Zorvik AI on ${new Date().toLocaleString()}</div>
          <script>
            window.onload = () => { window.print(); window.close(); }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-lg rounded-2xl bg-[#0a0a14] border border-white/[0.12] shadow-2xl overflow-hidden p-6">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-white/[0.06]">
          <div>
            <h3 className="text-lg font-medium text-white tracking-tight">Share & Export Conversation</h3>
            <p className="text-xs text-silver/50 font-light truncate max-w-[340px] mt-0.5">
              {session.title || 'Untitled Session'}
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-silver/40 hover:text-white hover:bg-white/[0.05] transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        {/* Share Options Grid */}
        <div className="grid grid-cols-1 gap-2.5 py-5">
          {/* 1. Copy Public Link */}
          <button
            onClick={handleCopyLink}
            className="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/[0.06] hover:border-iris/40 hover:bg-white/[0.04] transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-iris/10 text-iris group-hover:bg-iris group-hover:text-white transition-colors">
                <Link2 size={16} />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium text-white/90 group-hover:text-white">Copy Share Link</div>
                <div className="text-xs text-silver/40 font-light">Generate instant shareable link to this session</div>
              </div>
            </div>
            {copiedLink ? (
              <span className="flex items-center gap-1 text-xs font-mono text-emerald-400 bg-emerald-500/10 px-2 py-1 rounded-md">
                <Check size={12} /> Copied
              </span>
            ) : (
              <span className="text-xs font-mono text-silver/30 group-hover:text-iris">Link</span>
            )}
          </button>

          {/* 2. Download HTML Report (.html) */}
          <button
            onClick={handleDownloadHTMLReport}
            className="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/[0.06] hover:border-iris/40 hover:bg-white/[0.04] transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-cyan-500/10 text-cyan-400 group-hover:bg-cyan-600 group-hover:text-white transition-colors">
                <FileCode size={16} />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium text-white/90 group-hover:text-white">Download HTML Report</div>
                <div className="text-xs text-silver/40 font-light">Self-contained styled executive report with dark theme</div>
              </div>
            </div>
            <span className="text-xs font-mono text-silver/30 group-hover:text-iris">.html</span>
          </button>

          {/* 3. Download Markdown (.md) */}
          <button
            onClick={handleDownloadMarkdown}
            className="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/[0.06] hover:border-iris/40 hover:bg-white/[0.04] transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-purple-500/10 text-purple-400 group-hover:bg-purple-600 group-hover:text-white transition-colors">
                <Download size={16} />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium text-white/90 group-hover:text-white">Export Markdown (.md)</div>
                <div className="text-xs text-silver/40 font-light">Formatted with headers, code blocks & LaTeX math</div>
              </div>
            </div>
            <span className="text-xs font-mono text-silver/30 group-hover:text-iris">.md</span>
          </button>

          {/* 4. Export JSON */}
          <button
            onClick={handleDownloadJSON}
            className="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/[0.06] hover:border-iris/40 hover:bg-white/[0.04] transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400 group-hover:bg-indigo-600 group-hover:text-white transition-colors">
                <FileText size={16} />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium text-white/90 group-hover:text-white">Export JSON Data</div>
                <div className="text-xs text-silver/40 font-light">Raw structured chat transcript & timestamps</div>
              </div>
            </div>
            <span className="text-xs font-mono text-silver/30 group-hover:text-iris">.json</span>
          </button>

          {/* 5. Print / PDF */}
          <button
            onClick={handlePrint}
            className="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/[0.06] hover:border-iris/40 hover:bg-white/[0.04] transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 group-hover:bg-emerald-600 group-hover:text-white transition-colors">
                <Printer size={16} />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium text-white/90 group-hover:text-white">Print / Save as PDF</div>
                <div className="text-xs text-silver/40 font-light">Open print dialogue with clean typography</div>
              </div>
            </div>
            <span className="text-xs font-mono text-silver/30 group-hover:text-iris">PDF</span>
          </button>

          {/* 6. Copy Transcript to Clipboard */}
          <button
            onClick={handleCopyTranscript}
            className="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/[0.06] hover:border-iris/40 hover:bg-white/[0.04] transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-white/[0.05] text-silver group-hover:bg-white/20 group-hover:text-white transition-colors">
                <Copy size={16} />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium text-white/90 group-hover:text-white">Copy Transcript</div>
                <div className="text-xs text-silver/40 font-light">Full conversation text to your clipboard</div>
              </div>
            </div>
            {copiedText ? (
              <span className="flex items-center gap-1 text-xs font-mono text-emerald-400 bg-emerald-500/10 px-2 py-1 rounded-md">
                <Check size={12} /> Copied
              </span>
            ) : (
              <span className="text-xs font-mono text-silver/30 group-hover:text-iris">Copy</span>
            )}
          </button>
        </div>

        {/* Footer */}
        <div className="pt-3 border-t border-white/[0.06] flex items-center justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-white/[0.05] hover:bg-white/[0.1] text-xs font-medium text-white transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
